version: '3.3'
services:
  magento-db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/database/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  magento-adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - magento-db
  magento-php:
    build: ./.docker/php
    container_name: php-fpm
    volumes:
      - ./src:/var/www/magento/
    links:
      - magento-db
  magento-nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/conf:/etc/nginx/conf.d
      - ./.docker/nginx/logs:/var/log/nginx/
      - ./src:/var/www/magento/
    links:
      - magento-php
  magento-elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:7-debian-10'
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./.docker/elasticsearch:/bitnami/elasticsearch/data
  magento-rabbitmq:
   image: rabbitmq:management-alpine
   container_name: rabbitmq
   volumes:
    - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    - ./.docker/rabbitmq/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins
    - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
   environment:
     RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
   ports:
     - 5672:5672
     - 8090:15672
   links:
    - magento-nginx
